---
title: "Cleaning Swim Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Cleaning Swim Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(within)
```

We collect reports from people who went for a swim by asking this question:

> Where did you swim and how hot was it outside?

The data usually comes as a CSV file, which we read into a data frame.

```{r clean-data}
library(tidyverse)

infile <- "swim.csv"
original_dat <- read_csv(
  infile,
  col_types = cols(name = "c", where = "c", temp = "d")
)

lookup_table <- tribble(
  ~where,     ~english,
  "beach",    "US",
  "coast",    "US",
  "seashore", "UK",
  "seaside",  "UK"
)

dat <- original_dat %>%
  left_join(lookup_table, by = "where")

dat <- dat %>%
  mutate(
    temp = if_else(
      english == "US",
      (temp - 32) * 5/9,
      temp
    )
  )
dat

now <- Sys.time()
timestamp <- format(now, "%Y-%m-%d_%H-%M-%S")
cleaned_path <- sub("(.*)([.]csv$)", "\\1_clean\\2", infile)
outfile <- paste0(
  timestamp,
  "_",
  cleaned_path
)
write_csv(dat, outfile)
```
